# render.yaml
services:
  - type: web
    name: stem-retention-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:///stem_retention.db
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production

---

# Procfile
web: python app.py

---

# runtime.txt
python-3.11.0

---

# .gitignore
# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
ENV/
env.bak/
venv.bak/

# Flask
instance/
.webassets-cache

# Database
*.db
*.sqlite

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Environment variables
.env
.env.local
.env.production

# Logs
*.log

# Machine Learning Models
*.pkl
risk_model.pkl

# Temporary files
*.tmp
*.temp